// Mocks generated by Mockito 5.4.6 from annotations
// in ecotur_app/test/ui_render_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui' as _i8;

import 'package:ecotur_app/models/tourist_service_model.dart' as _i4;
import 'package:ecotur_app/services/auth_service.dart' as _i5;
import 'package:ecotur_app/services/catalog_service.dart' as _i2;
import 'package:ecotur_app/services/session_service.dart' as _i6;
import 'package:ecotur_app/services/user_service.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [CatalogService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCatalogService extends _i1.Mock implements _i2.CatalogService {
  MockCatalogService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.TouristService>> fetchServices() =>
      (super.noSuchMethod(
            Invocation.method(#fetchServices, []),
            returnValue: _i3.Future<List<_i4.TouristService>>.value(
              <_i4.TouristService>[],
            ),
          )
          as _i3.Future<List<_i4.TouristService>>);

  @override
  _i3.Future<Map<String, dynamic>> createService(
    Map<String, dynamic>? serviceData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createService, [serviceData]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<List<_i4.TouristService>> fetchInactiveServices() =>
      (super.noSuchMethod(
            Invocation.method(#fetchInactiveServices, []),
            returnValue: _i3.Future<List<_i4.TouristService>>.value(
              <_i4.TouristService>[],
            ),
          )
          as _i3.Future<List<_i4.TouristService>>);

  @override
  _i3.Future<List<_i4.TouristService>> fetchDeletedServices() =>
      (super.noSuchMethod(
            Invocation.method(#fetchDeletedServices, []),
            returnValue: _i3.Future<List<_i4.TouristService>>.value(
              <_i4.TouristService>[],
            ),
          )
          as _i3.Future<List<_i4.TouristService>>);

  @override
  _i3.Future<Map<String, dynamic>> activateService(int? serviceId) =>
      (super.noSuchMethod(
            Invocation.method(#activateService, [serviceId]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> deactivateService(int? serviceId) =>
      (super.noSuchMethod(
            Invocation.method(#deactivateService, [serviceId]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> recoverService(int? serviceId) =>
      (super.noSuchMethod(
            Invocation.method(#recoverService, [serviceId]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> softDeleteService(int? serviceId) =>
      (super.noSuchMethod(
            Invocation.method(#softDeleteService, [serviceId]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> updateService(
    int? serviceId,
    Map<String, dynamic>? serviceData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateService, [serviceId, serviceData]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i5.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<Map<String, dynamic>> login(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> verifyEmail(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#verifyEmail, [token]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);
}

/// A class which mocks [SessionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSessionService extends _i1.Mock implements _i6.SessionService {
  MockSessionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  String get userRole =>
      (super.noSuchMethod(
            Invocation.getter(#userRole),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#userRole),
            ),
          )
          as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i3.Future<void> establishSession(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#establishSession, [token]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> destroySession() =>
      (super.noSuchMethod(
            Invocation.method(#destroySession, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> checkExistingSession() =>
      (super.noSuchMethod(
            Invocation.method(#checkExistingSession, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TouristService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTouristService extends _i1.Mock implements _i9.UserService {
  MockUserService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<Map<String, dynamic>> registerTourist({
    required String? cedula,
    required String? email,
    required String? password,
    required String? firstName,
    required String? lastName,
    required String? phone,
    required bool? dataConsent,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#registerTourist, [], {
              #cedula: cedula,
              #email: email,
              #password: password,
              #firstName: firstName,
              #lastName: lastName,
              #phone: phone,
              #dataConsent: dataConsent,
            }),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> fetchMyProfile() =>
      (super.noSuchMethod(
            Invocation.method(#fetchMyProfile, []),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);
}
