name: ecotur_app
description: "Cliente móvil oficial de Ecotur Asoprado - Prototipo MVP"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  shared_preferences: ^2.5.5
  flutter_dotenv: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4      # Dependencia para mocking determinista en pruebas
  build_runner: ^2.4.8 # Generador de código para los mocks y null-safety
  flutter_lints: ^6.0.0 # Reglas estrictas de análisis estático de Google

flutter:
  uses-material-design: true

  assets:
    - .env

  fonts:
    - family: Space Grotesk
      fonts:
        - asset: assets/fonts/Space_Grotesk/static/SpaceGrotesk-Regular.ttf
        - asset: assets/fonts/Space_Grotesk/static/SpaceGrotesk-Bold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/static/Inter_18pt-Regular.ttf
        - asset: assets/fonts/Inter/static/Inter_18pt-SemiBold.ttf
          weight: 600