# ==============================================================================
# PIPELINE CD: FRONTEND ECOTUR ASOPRADO
# Propósito: Despliegue estático a los servidores de borde (CDN) de Azure.
# Se dispara EXCLUSIVAMENTE tras un merge exitoso a las ramas principales.
# ==============================================================================

trigger:
  branches:
    include:
      - develop
      - staging
      - main

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}:
    ENTORNO: 'VG-ECOTUR-DEV'
  ${{ if eq(variables['Build.SourceBranchName'], 'staging') }}:
    ENTORNO: 'VG-ECOTUR-STG'
  ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
    ENTORNO: 'VG-ECOTUR-MAIN'

stages:
  - stage: Deploy_Web
    displayName: 'Despliegue a Azure Static Web Apps'
    jobs:
      - job: Compilar_y_Desplegar
        variables:
          - group: ${{ variables.ENTORNO }}

        steps:
          - script: |
              git clone https://github.com/flutter/flutter.git -b stable --depth 1
              echo "##vso[task.prependpath]$(pwd)/flutter/bin"
            displayName: 'Instalar Flutter SDK'

          - script: flutter pub get
            displayName: 'Instalar dependencias'

          - script: |
              echo "Generando archivo .env vacío para el empaquetador de Flutter..."
              touch .env
            displayName: 'Setup: Inyectar .env Dummy'

          - script: flutter build web --release --dart-define=API_URL=$(DEPLOYED_BACKEND)
            displayName: 'CD: Construir Flutter Web Estático'

          - task: AzureStaticWebApp@0
            displayName: 'CD: Publicar en Azure SWA'
            inputs:
              app_location: '/'
              output_location: 'build/web'
              skip_api_build: true
              azure_static_web_apps_api_token: $(SWA_DEPLOYMENT_TOKEN)